name: Deploy Front-end

on:
  push:
    branches:
      - Re-init

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t 6030631621/candidate-test:latest .

    - name: Push Docker Image
      run: docker push 6030631621/candidate-test:latest